### ISSUE TITLE
Login and Sign-in page there is not password visible option which is not a good user experience

### ISSUE THREAD

**Issue by Kunj05** [MitulSonagara/truth-tunnel#6] opened 2024-10-02 09:10 UTC
Description: The current login and signup pages do not include a password visibility toggle, which can lead to user frustration and increased chances of errors when entering passwords.

Current Behavior:
Users cannot see their password while typing, making it difficult to ensure accuracy.

Expected Behavior:
A toggle option should be available next to the password input fields that allows users to view or hide their passwords.

Additional Notes:
I am willing to work on this feature and provide the necessary implementation.

Checklist

- [x]  I have checked the existing issues
- [x]  I have read the Contributing Guidelines
- [x]  I'm a GSSoC'24-Extd contributor
- [x]  I'm a Hacktoberfest'24 contributor
- [x]  I am willing to work on this issue

**Comment by MitulSonagara** [comment] 2024-10-02 09:20
@Kunj05 i'm assigning this to you.

Keep in mind that this project is not under hacktoberfest so you will not receive label for that

**Comment by Deshmukh-Ayush** [comment] 2024-10-04 17:40
Subject: Request to Assign Issue

Hi Project Manager

I hope you're doing well. I noticed the issue is still open and would like to request that it be assigned to me. I’m eager to work on this and am confident I can deliver a good solution.

Could you please assign it to me as soon as possible?

Thank you for your time and consideration. I’m looking forward to your response.

Best regards,
Ayush Deshmukh

**Comment by Deshmukh-Ayush** [comment] 2024-10-04 17:51
Subject: Request to Assign Issue

Hi @MitulSonagara 

I hope you're doing well. I noticed this issue is still open and would like to request please assign this issue to me. I’m eager to work on this and am confident I can deliver a solid solution promptly.

Could you please assign it to me as soon as possible?

Thank you for your time and consideration. I’m looking forward to your response.

Best regards,
Ayush Deshmukh

**Closed as completed** 2024-10-08 09:43 UTC
Labels: enhancement, level2, hacktoberfest-accepted, gssoc-ext
